---
- name: Create dashdot container
  community.docker.docker_container:
    name: dashdot
    image: mauricenino/dashdot:latest
    restart_policy: unless-stopped
    state: started
    pull: true
    privileged: true
    networks:
      - name: homelab
    volumes:
      - "/:/mnt/host:ro"
    env:
      DASHDOT_ACCEPT_OOKLA_EULA: "true"
    labels:
      traefik.enable: "true"
      traefik.http.routers.dash.entrypoints: "web, websecure"
      traefik.http.routers.dash.rule: "Host(`dash.{{ domain }}`)"
      traefik.http.services.dash.loadbalancer.server.port: "3001"
